name: Bug Report
description: File a bug report to help us improve Zeus SDK
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize client with '...'
        2. Call method '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: python
      placeholder: |
        from zeus import ZeusClient
        
        zeus = ZeusClient(api_key="your_key")
        # Your code here

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant error messages or stack traces
      render: shell
      placeholder: Paste error logs here

  - type: input
    id: sdk-version
    attributes:
      label: Zeus SDK Version
      description: What version of Zeus SDK are you using?
      placeholder: "0.1.1"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.5"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, links, etc.)
      placeholder: Any additional information

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
